dataset_path: './dataset/metamorphosis_clean.txt'
model_path: './trained_model/mini_llm.pth'

hyperparameters:
  embedding_dim: 16
  hidden_dim: 32
  num_layers: 2
  learning_rate: 0.001
  epochs: 160